server:
    error:
        include-message: always
        include-binding-errors: always

spring:
    jpa:
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:mysql://unitask-mysql.mysql.database.azure.com/jwt_impl
        username: TeamOneMySQL
        password: Un1taskerz
        driver-class-name: com.mysql.cj.jdbc.Driver
    mail:
        host: smtp.gmail.com
        port: 587
        username: unitask370@gmail.com
        password: dxecgnicicrgsosy
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

# App Properties
unitask:
    app:
        jwtSecret: "======================unitask=Spring==========================="
        jwtExpirationMs: 86400000