name: Build and deploy Jekyll site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build and deploy Jekyll site
      uses: helaili/jekyll-action@2.0.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Copy frontend documentation
      run: cp -r doc/frontend/* _site/frontend/

    - name: Copy backend documentation
      run: cp -r doc/backend/* _site/backend/
