name: Build and deploy Jekyll site for documentations

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build and deploy Jekyll site
      uses: jekyll/actions-pages@v1 
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Ruby environment
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'  # Specify the Ruby version here

    - name: Build Jekyll site
      run: |
        bundle install
        bundle exec jekyll build

    - name: Copy frontend documentation
      run: cp -r doc/frontend/* _site/frontend/

    - name: Copy backend documentation
      run: cp -r doc/backend/* _site/backend/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
